### ISSUE TITLE
Logs are not written

### ISSUE THREAD

**Issue by 4OTbIPE** [reportportal/agent-dotnet-reqnroll#3]
After migration from SpecFlow to Reqnroll, and from Specflow-Agent to Reqnroll-Agent, logs with NLog and ReportPortal.NLog logs have stopped being written to the ReportPortal.

There is a line in the ReportPortal.Shared logs "1-Automation : Cannot track OnBeforeLaunchStarting event". Maybe it has something to do with it.

**Comment by nvborisenko** [comment]
@4OTbIPE please expand the entire error message including stacktrace.

**Comment by 4OTbIPE** [comment]
@nvborisenko ReportPortal.Shared.*****.log:

> AnalyticsReportEventsObserver Error: 0 : 13:41:41.9926371 : 1-Automation : Cannot track OnBeforeLaunchStarting event: System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://10.0.25.3:8080/' failed with status code '407'."
>    at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at ReportPortal.Shared.Extensibility.Embedded.Analytics.AnalyticsReportEventsObserver.<>c__DisplayClass26_0.<<ReportEventsSource_OnBeforeLaunchStarting>b__0>d.MoveNext()

But I discovered that when using SpecFlow and the corresponding agent, the same log file with the same contents is created. But at the same time, the logs are written correctly to the portal. However, when switching to Rocknroll and the corresponding agent, the logs stop being written. I would like to note that logs specifically from NLog (logger.Debug(), etc.) are not written. The Reqnroll steps themselves are displayed correctly in the portal, as are AssertionExceptions and their text and stack trace.

I also noticed that in ReportPortal.json you need to specify the apiKey, but IntelliSense also asks you to specify the authentication field

**Comment by nvborisenko** [comment]
Reproduced, tried to fix - no success. Please be patient, seems it will not be quick-fix.

**Comment by nvborisenko** [comment]
Just verified with Reqnroll 2.0.3 (NUnit provider) - it works:

```csharp
[Given("the first number is {int}")]
public void GivenTheFirstNumberIs(int number)
{
    ReportPortal.Shared.Context.Current.Log.Info("my test message");
    ReportPortal.Shared.Context.Current.Log.Info("my next test message");
}

[Given("the second number is {int}")]
public void GivenTheSecondNumberIs(int number)
{
    ReportPortal.Shared.Context.Current.Log.Info("my test message");
}
```

![image](https://github.com/user-attachments/assets/e7b03997-b82d-4f58-9ae7-5eba5bae3ddf)

I guess it was fixed by Reqnroll team.
